-- I suggest to leave it blank because this index duplicates PK index created automatically
-- If we really need to re-create it, it should be done by:
-- CREATE INDEX execution_outcomes_receipt_id_idx ON execution_outcomes (receipt_id);
