DROP INDEX action_receipt_actions_receipt_predecessor_account_id_idx;
DROP INDEX action_receipt_actions_receipt_receiver_account_id_idx;
DROP INDEX action_receipt_actions_receipt_included_in_block_timestamp_idx;
