CREATE INDEX action_receipt_actions_receipt_predecessor_account_id_idx ON action_receipt_actions(receipt_predecessor_account_id);
CREATE INDEX action_receipt_actions_receipt_receiver_account_id_idx ON action_receipt_actions(receipt_receiver_account_id);
CREATE INDEX action_receipt_actions_receipt_included_in_block_timestamp_idx ON action_receipt_actions(receipt_included_in_block_timestamp);
