steps:
  - command: "source ~/.cargo/env && cargo fmt --all -- --check"
    label: "Formatter"
    
  - command: "source ~/.cargo/env && cargo clippy"
    label: "Linter"
    
  - command: "source ~/.cargo/env && cargo test"
    label: "Tests"

  - command: "fossa init && fossa analyze --server-scan && fossa test"
    label: "Fossa"
