steps:
  - label: publish docker
    command: ./scripts/docker-release.sh
    branches: "master | mhala-docker"
    plugins:
      - docker-login#v2.0.1:
          username: nearprotocol
          password-env: DOCKER_LOGIN_PASSWORD
