-- These changes should be applied manually if needed

-- CREATE UNIQUE INDEX CONCURRENTLY assets__fungible_idx_tmp
--     ON assets__fungible_token_events (emitted_for_receipt_id,
--                                       emitted_at_block_timestamp,
--                                       emitted_in_shard_id,
--                                       emitted_index_of_event_entry_in_shard,
--                                       emitted_by_contract_account_id,
--                                       amount,
--                                       event_kind,
--                                       token_old_owner_account_id,
--                                       token_new_owner_account_id,
--                                       event_memo);
--
-- CREATE UNIQUE INDEX CONCURRENTLY assets__fungible_token_events_unique
--     ON assets__fungible_token_events (emitted_for_receipt_id, emitted_index_of_event_entry_in_shard);
--
-- -- This block runs ~1 sec
-- BEGIN TRANSACTION;
-- ALTER TABLE assets__fungible_token_events
--     DROP CONSTRAINT assets__fungible_token_events_pkey;
-- -- This command will automatically rename assets__fungible_idx_tmp to assets__fungible_token_events_pkey
-- ALTER TABLE assets__fungible_token_events
--     ADD CONSTRAINT assets__fungible_token_events_pkey PRIMARY KEY USING INDEX assets__fungible_idx_tmp;
-- COMMIT;
