# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
# Temporary add this if you need to update something in deprecated schema (and comment filter section)
# schema = "deprecated"
# patch_file = "src/schema.patch"
import_types = ["diesel::sql_types::*", "crate::models::enums::*"]
# Exclicitly setting `only_tables` to avoid technical tables created by diesel to be included in schema
filter = { only_tables = [
    "blocks",
    "chunks",
    "receipts",
    "data_receipts",
    "action_receipts",
    "action_receipt_actions",
    "action_receipt_input_data",
    "action_receipt_output_data",
    "execution_outcomes",
    "execution_outcome_receipts",
    "transactions",
    "transaction_actions",
    "accounts",
    "access_keys",
    "aggregated__circulating_supply",
    "assets__non_fungible_token_events",
    # It does not work, diesel track only one schema (public by default). But let's leave it here as a doc
    # "deprecated.account_changes",
    # "deprecated.assets__fungible_token_events"
] }
