-- TRANSACTIONS
DROP INDEX transactions_signer_account_id_idx;
DROP INDEX transactions_signer_public_key_idx;

-- RECEIPTS
DROP INDEX receipts_predecessor_account_id_idx;
DROP INDEX receipts_receiver_account_id_idx;

DROP INDEX data_receipts_receipt_id_idx;
DROP INDEX action_receipt_signer_account_id_idx;

DROP INDEX action_receipt_output_data_output_from_receipt_id_idx;
DROP INDEX action_receipt_output_data_receiver_account_id_idx;

DROP INDEX action_receipt_input_data_input_to_receipt_id_idx;
DROP INDEX action_receipt_input_data_input_data_id_idx;

ALTER INDEX action_receipt_output_data_output_data_id_idx RENAME TO action_output_data_id_idx;
ALTER INDEX transactions_included_in_block_timestamp_idx RENAME TO tx_timestamp_idx;
ALTER INDEX chunks_included_in_block_hash_idx RENAME TO chunks_block_hash_idx;
CREATE INDEX blocks_hash_idx ON blocks(block_hash);
